CREATE TABLE IF NOT EXISTS stg_ads_info (
    end_time DateTime,
    create_time DateTime,
    change_time DateTime,
    start_time DateTime,
    auto_params_cpm UInt32,
    auto_params_subject_name String,
    auto_params_subject_id UInt32,
    auto_params_menu_id UInt32,
    auto_params_nm UInt32,
    auto_params_active_carousel Bool,
    auto_params_active_recom Bool,
    auto_params_active_booster Bool,
    auto_params_nm_cpm_nm UInt32,
    auto_params_nm_cpm_cpm UInt32,
    name String,
    daily_budget UInt32,
    advert_id UInt32,
    status UInt32,
    type UInt32,
    payment_type UInt32,
    task_id UUID,
    ts DateTime
) ENGINE = MergeTree()
ORDER BY (advert_id, name);