CREATE TABLE IF NOT EXISTS stg_ads_info (
    end_time DateTime('UTC'),
    create_time DateTime('UTC'),
    change_time DateTime('UTC'),
    start_time DateTime('UTC'),
    bid_type UInt32 DEFAULT NULL,
    search_pluse_state Bool,
    united_params_catalog_cpm UInt32 DEFAULT NULL,
    united_params_search_cpm UInt32 DEFAULT NULL,
    united_params_subject_id UInt32 DEFAULT NULL,
    united_params_subject_name String DEFAULT NULL,
    united_params_menu_ids UInt32 DEFAULT NULL,
    united_params_menus_id UInt32 DEFAULT NULL,
    united_params_menus_name String DEFAULT NULL,
    united_params_nms UInt32 DEFAULT NULL,
    auction_multibids_nm UInt32 DEFAULT NULL,
    auction_multibids_bid UInt32 DEFAULT NULL,
    auto_params_cpm UInt32 DEFAULT NULL,
    auto_params_subject_name String DEFAULT NULL,
    auto_params_subject_id UInt32 DEFAULT NULL,
    auto_params_menu_ids UInt32 DEFAULT NULL,
    auto_params_nms UInt32 DEFAULT NULL,
    auto_params_active_carousel Bool DEFAULT NULL,
    auto_params_active_recom Bool DEFAULT NULL,
    auto_params_active_booster Bool DEFAULT NULL,
    auto_params_nm_cpm_nm UInt32 DEFAULT NULL,
    auto_params_nm_cpm_cpm UInt32 DEFAULT NULL,
    params_intervals_begin UInt32 DEFAULT NULL,
    params_intervals_end UInt32 DEFAULT NULL,
    params_price UInt32 DEFAULT NULL,
    params_subject_id UInt32 DEFAULT NULL,
    params_subject_name String DEFAULT NULL,
    params_nms_nm UInt32 DEFAULT NULL,
    params_nms_active Bool DEFAULT NULL,
    params_active Bool DEFAULT NULL,
    name String,
    daily_budget UInt32,
    advert_id UInt32,
    status UInt32,
    type UInt32,
    payment_type String,
    task_id UUID,
    ts DateTime('UTC')
) ENGINE = MergeTree()
ORDER BY (advert_id, name);