CREATE TABLE IF NOT EXISTS default.stg_fbs (
    address_full_address String,
    address_longtitude Float64,
    address_latitude Float64,
    scan_price UInt32,
    delivery_type String,
    supply_id String,
    order_uid String,
    article String,
    color_code String,
    rid String,
    created_at DateTime('UTC'),
    offices String,
    skus String,
    id UInt64,
    warehouse_id UInt32,
    office_id UInt64,
    nm_id UInt64,
    chrt_id UInt64,
    price UInt32,
    converted_price UInt32,
    currency_code UInt32,
    converted_currency_code UInt32,
    cargo_type UInt8,
    comment String,
    is_zero_order Boolean,
    is_b2b Boolean,
    task_id UUID,
    ts DateTime('UTC')
) ENGINE = MergeTree
ORDER BY (order_uid, rid, created_at);