CREATE TABLE IF NOT EXISTS stg_cards (
    nm_id UInt32,
    imt_id UInt32,
    nm_uuid UUID,
    subject_id UInt32,
    subject_name String,
    vendor_code String,
    brand String,
    title String,
    description String,
    need_kiz Bool,
    photos String DEFAULT NULL,
    video String,
    wholesale_enabled Bool DEFAULT NULL,
    wholesale_quantum UInt64 DEFAULT NULL,
    dimensions_length UInt32,
    dimensions_width UInt32,
    dimensions_height UInt32,
    dimensions_weight_brutto UInt32,
    dimensions_is_valid Bool,
    characteristics_id UInt32,
    characteristics_name String,
    characteristics_value String,
    sizes_chrt_id UInt32,
    sizes_tech_size String,
    sizes_wb_size String,
    sizes_skus String,
    tags_id UInt32,
    tags_name String,
    tags_color String,
    created_at DateTime('UTC'),
    updated_at DateTime('UTC'),
    task_id UUID,
    ts DateTime('UTC')
) ENGINE = MergeTree()
ORDER BY (nm_id, title, nm_uuid, imt_id);