CREATE TABLE IF NOT EXISTS stg_cards (
    nm_id UInt32,
    imt_id UInt32,
    nm_uuid UUID,
    subject_id UInt32,
    subject_name String DEFAULT NULL,
    vendor_code String DEFAULT NULL,
    brand String DEFAULT NULL,
    title String DEFAULT NULL,
    description String DEFAULT NULL,
    need_kiz Boolean,
    photos String DEFAULT NULL,
    video String DEFAULT NULL,
    wholesale_enabled Boolean DEFAULT NULL,
    wholesale_quantum UInt64 DEFAULT NULL,
    dimensions_length UInt32,
    dimensions_width UInt32,
    dimensions_height UInt32,
    dimensions_weight_brutto UInt32,
    dimensions_is_valid Boolean,
    characteristics_id UInt32,
    characteristics_name String DEFAULT NULL,
    characteristics_value String DEFAULT NULL,
    sizes_chrt_id UInt32,
    sizes_tech_size String DEFAULT NULL,
    sizes_wb_size String DEFAULT NULL,
    sizes_skus String DEFAULT NULL,
    tags_id UInt32,
    tags_name String DEFAULT NULL,
    tags_color String DEFAULT NULL,
    created_at DateTime('UTC'),
    updated_at DateTime('UTC'),
    task_id UUID,
    ts DateTime('UTC')
) ENGINE = MergeTree()
ORDER BY (nm_id, title, nm_uuid, imt_id);