CREATE TABLE IF NOT EXISTS stg_ads_stats (
    advert_id UInt32,
    atbs UInt32,
    canceled UInt32,
    clicks UInt32,
    cpc Float32,
    cr Float32,
    ctr Float32,
    orders UInt32,
    shks UInt32,
    sum Float32,
    sum_price UInt32,
    views UInt32,
    booster_stats_avg_position UInt32 DEFAULT NULL,
    booster_stats_date DateTime('UTC') DEFAULT NULL,
    booster_stats_nm UInt32 DEFAULT NULL,
    days_atbs UInt32,
    days_canceled UInt32,
    days_clicks UInt32,
    days_cpc Float32,
    days_cr Float32,
    days_ctr Float32,
    days_orders UInt32,
    days_date DateTime('UTC'),
    days_shks UInt32,
    days_sum Float32,
    days_sum_price Float32,
    days_views UInt32,
    days_apps_app_type UInt32,
    days_apps_atbs UInt32,
    days_apps_canceled UInt32,
    days_apps_clicks UInt32,
    days_apps_cpc Float32,
    days_apps_cr Float32,
    days_apps_ctr Float32,
    days_apps_orders UInt32,
    days_apps_shks UInt32,
    days_apps_sum Float32,
    days_apps_sum_price Float32,
    days_apps_views UInt32,
    days_apps_nms_atbs UInt32,
    days_apps_nms_canceled UInt32,
    days_apps_nms_clicks DateTime('UTC'),
    days_apps_nms_cpc Float32,
    days_apps_nms_cr Float32,
    days_apps_nms_ctr Float32,
    days_apps_nms_name String,
    days_apps_nms_nm_id UInt32,
    days_apps_nms_orders UInt32,
    days_apps_nms_shks UInt32,
    days_apps_nms_sum Float32,
    days_apps_nms_sum_price Float32,
    days_apps_nms_views UInt32,
    task_id UUID,
    ts DateTime('UTC'),
) ENGINE = MergeTree()
ORDER BY (
        advert_id,
        days_apps_nms_nm_id,
        days_apps_nms_name
    );